services:
  postgres:
    image: postgres:16
    container_name: shortener_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "54302:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
