### POST /api/v1/links/create
POST http://localhost:8080/api/v1/links/create
Content-Type: application/json

{
  "url": "http://google.com/"
}

### GET /api/v1/links/:shorten-url
GET http://localhost:8080/api/v1/links/MEWooaGf
Content-Type: application/json

### GET /api/v1/links
GET http://localhost:8080/api/v1/links?is_active=true&sort_by=visits&sort_order=desc
Content-Type: application/json