### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=GoLand

### POST /api/v1/links/create
POST http://localhost:8080/api/v1/links/create
Content-Type: application/json

{
  "url": "http://habr.com/"
}
