### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=GoLand

###

### POST /schemas
POST http://localhost:8080/api/v1/links/create
Content-Type: application/json

{
  "name": "schema-custo123123m12"
}
